############# French navigation ##############

# main menu
[[main]]
name = "Valori"
url = "values/"
weight = 2

[[main]]
name = "Vantaggi"
url = "advantages/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Team"
url = "team/"
weight = 6

[[main]]
name = "Contatti"
url = "contact/"
weight = 7

[[main]]
name = "Ospitalit√†"
url = "booking/"
weight = 8

# footer menu
[[footer]]
name = "Terms of Service"
url = "terms/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
